using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Api.AricsNotes
{
    public class AricNotes
    {
        //Lets make DTO'S (data transfer objects) yaayyy!!!!
        // we have a model that represent the domain of our application & model that represents the data handeld by our api are seperate conserns and must be handled separately. if not we would break the api for users when we modify fields from our domain model (our model for the project)

        //we use auto mapper to convert objects from diffrent models 


        //when trying to submit a ticket through post request... dont submit an id... this is auto generated by Identity... if you try to do it, it will raise an error because the primary key column is set to auto-incrament... & Identity insert is set to off... for more info see -> https://appuals.com/how-to-fix-the-error-cannot-insert-explicit-value-for-identity-column-in-table-when-identity_insert-is-set-to-off/
    }
}
